language: bash

install: make

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

jobs:
  include:
    - stage: "build"
      name: "Docker build"
      script: make docker-build

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  script: make docker-push
  on:
    branch: master
