language: bash

install: make

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

jobs:
  include:
    - stage: "build"
      name: "Docker build"
      script: make docker-build
    - stage: deploy
      name: "push to Dockerhub"
      script: make docker-push

stages:
  stages:
  - build
  - name: deploy
    if: branch = master