name: build-only
on:
  pull_request:
    branches:
      - '!master'

jobs:
  build-only:
    name: build-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install make
      - run: make docker-build
